### ISSUE TITLE
Renaming diesel crate causes issue with derive-enum

### ISSUE THREAD

**Issue by JeanMertz** [adwhit/diesel-derive-enum#29]
I've got the following `Cargo.toml`:

```toml
[package]
...

[dependencies]
diesel_crate = { version = "1", optional = true, package = "diesel" }
diesel-derive-enum = { version = "0.4", features = ["sqlite"], optional = true }

[features]
diesel = ["diesel_crate", "diesel-derive-enum"]
```

A `feature` can't have the same name as a `dependency`, so I rename the `diesel` crate to `diesel_crate`. In the library, I then use `use diesel_crate::prelude::*` for example.

This works, but this library can't handle that situation, because it doesn't explicitly depend on diesel, and requires you to manually add that dependency, which it then expects to be named `diesel`.

Now... when I started typing this, I wanted to propose adding diesel as a dependency, but then I realised that would probably require you to enable all features of diesel for this crate to work in all situations, right? 🤔

So yeah, I guess I'll go ahead and create this issue anyway, but unless there's something that Cargo provides to solve this, there's probably no way for this to work, without requiring anyone depending on this crate to automatically include all features of Diesel...
